### ISSUE TITLE
Swap background image with video 

### ISSUE THREAD

**Issue by justinLifelike** [adcimon/segmentation-ndi#1]
Dear Adcimon, 

I would like to swap the background image with a video but I cant seem to find a way. 
I am not the best programmer out there. 

Could you help me out here? 

Thanks in advance!

**Comment by adcimon** [comment]
Hi!

The project is based on https://github.com/keijiro/SelfieBarracuda, I would try to check his source code.
Specifically the **_bgImage** variable of the **Compositor.cs** (https://github.com/keijiro/SelfieBarracuda/blob/main/Assets/Compositor.cs#L12) which is a **Texture2D**  and feed that variable with a video played using a **VideoPlayer** (https://docs.unity3d.com/ScriptReference/Video.VideoPlayer.html).
